#!/usr/bin/python3
# COMP3311 20T2 Final Exam
# Q6: discography for one group, given by Groups.id

import sys
import psycopg2

# ... put helper functions here ...

db = None
cur = None
usage = f"Usage: {sys.argv[0]} GroupID"

# process command-line args

if len(sys.argv) < 2:
   print(usage)
   exit(1)
groupID = sys.argv[1]
if not groupID.isnumeric():
   print(usage)
   exit(1)

try:
   db = psycopg2.connect("dbname=music")

   grp = """
   select name
   from groups
   where id = %s
   """
   cur = db.cursor()
   cur.execute(grp, [groupID])
   gname = cur.fetchone()
   print(f"Discography for {gname}")
   
   alb = """
      select title, year, genre, id
      from Albums
      where made_by = %s
   """
   cur.execute(alb, [groupID])
   albums = cur.fetchall()
   for title, year, genere, aId in albums:
      print('--------------------')
      print(f"{title} (year) (genre)")
      print('--------------------')
      qSongs = """
         select trackNo, title, length
         from Songs
         where on_album = %s
      """
      # cur.execute(qSongs, [aId])
      # Songs = cur.fetchall()
      # for 
      # printf("%2d. %s (%d:%02d)\n", trackno, title, minutes, seconds)
   

# except psycopg2.Error as err:
#    print("DB error: ", err)
finally:
   if cur:
       cur.close()
   if db:
      db.close()

